language: python
python:
- 2.7

before_script:
- sudo apt-get install python-virtualenv nodejs
- cd core/src/doc
- virtualenv --distribute --no-site-packages env
- env/bin/pip install -r requirements
- cd -
- cd core/tests
- virtualenv --distribute --no-site-packages env
- env/bin/pip install CherryPy==3.6.0 jasmine-core==2.2.0 jasmine==2.2.0
- cd -

script:
- cd core/tests
- env/bin/jasmine-ci --browser phantomjs
- cd -
- ./travis.sh

notifications:
  email:
    recipients:
    - c2cgeoportal@camptocamp.com
